version: "3.7"

services:
  server:
    build: ./server
    container_name: server_container_dev
    # dockerfile: Dockerfile.dev
    image: server_img_dev
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - web_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    container_name: web_container_dev
    image: web_img_dev
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app/
      # - /app/node_modules
    depends_on:
      - server
    networks:
      - web_network
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  server:
  web:

networks:
  web_network: