name: Docker Compose Actions Workflow

on:
  push:
<<<<<<< HEAD
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
=======
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]
>>>>>>> Dev
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: linuxserver/docker-compose:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d --build

<<<<<<< HEAD

=======
>>>>>>> Dev
